server:
  port: 9000

spring:
  application:
    name: order-service

  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: localhost:8848
        # 指定集群名称
        cluster-name: BJ
        metadata:
          version: v1

